restrict ingress access

diff --git a/devops/ado/pipeline.yaml b/devops/ado/pipeline.yaml
--- a/devops/ado/pipeline.yaml
+++ b/devops/ado/pipeline.yaml
@@ -84,6 +84,13 @@ stages:
             --name $(ACR_NAME) \
             --source $(ACR_NAME)/$(imgname):$(majorVersion).$BUILD_BUILDID \
             --image $(imgname):latest
+    - task: CmdLine@2
+      displayName: Get client IP address
+      inputs:
+        script: |
+          IP=($(curl -s http://ipinfo.io/json | jq -r '.ip'))
+          echo "This Microsoft hosted agent public IP is: ${IP}"
+          echo "##vso[task.setvariable variable=AGENT_IP]$(curl -s http://ipinfo.io/json | jq -r '.ip')"
     - task: AzureCLI@2
       displayName: "Create Container App"
       inputs:
@@ -115,6 +122,39 @@ stages:
             --resource-group $(RESOURCE_GROUP) \
             --target-port 3500 \
             --transport auto
+    - task: AzureCLI@2
+      displayName: Restrict access to container app ingress
+      inputs:
+        azureSubscription: $(SERVICE_CONNECTION)
+        scriptType: "bash"
+        scriptLocation: inlineScript
+        inlineScript: |
+          set -e
+            az containerapp ingress access-restriction set \
+              -n $(imgname) \
+              -g $(RESOURCE_GROUP) \
+              --rule-name ado-client \
+              --ip-address $(curl -s http://ipinfo.io/json | jq -r '.ip') \
+              --description "Allow access from ADO client" \
+              --action Allow
+    - task: AzureCLI@2
+      displayName: Test container app ingress
+      inputs:
+        azureSubscription: $(SERVICE_CONNECTION)
+        scriptType: "bash"
+        scriptLocation: inlineScript
+        inlineScript: |
+          set -e
+          FQDN=$(az containerapp ingress show -n $(imgname) -g $(RESOURCE_GROUP) | jq -r ".fqdn")
+          echo "##vso[task.setvariable variable=FQDN;]$FQDN"
+          curl -w '%{http_code}\n' -s -LI  https://${FQDN}/albums
+          CODE=$(curl -w '%{http_code}\n' -s -o /dev/null -LI  https://${FQDN}/albums)
+          if [[ "$CODE" -ne 200 ]] ; then
+            echo "Service returened error code: $CODE"
+            exit 1
+          else
+            echo "Service is available with code: $CODE"
+          fi
     - task: AzureCLI@2
       displayName: "Cleanup container app"
       inputs:
